In [1]:
import gym
import numpy as np
import tensorflow as tf
from collections import deque, namedtuple
from tensorflow import keras
import matplotlib.pyplot as plt


In [2]:
class Model(keras.Model):
    def __init__(self, action_size) -> None:
        super(Model, self).__init__()
        self.layer1 = keras.layers.Dense(64, activation = 'relu')
        self.layer2 = keras.layers.Dense(64, activation = 'relu')
        
        self.actor = keras.layers.Dense(action_size, activation = 'softmax')
        self.critic = keras.layers.Dense(1)
        
    def call(self,input):
        
        x = self.layer1(input)
        x = self.layer2(x)
        
        #Action Distribution
        actor = self.actor(x)
        
        #Value of rollout of rewards
        critic = self.critic(x)
        
        return actor, critic

In [3]:
# model = Model(4)

In [4]:
env = gym.make("LunarLander-v2", continuous = True)

In [5]:
env.action_space.sample()

array([ 0.8322714 , -0.67001766], dtype=float32)

In [6]:
env.observation_space

Box(-inf, inf, (8,), float32)

In [7]:
for i in range(10):
    state = env.reset()
    while True:
        action = env.action_space.sample()
        env.render()
        state_p, reward, done, _ = env.step(action)
        if done:
            break

In [33]:
env.close()

In [54]:
space = env.reset()

In [55]:
space

array([ 0.00311222,  1.3986368 ,  0.3152082 , -0.54591626, -0.0035994 ,
       -0.07139947,  0.        ,  0.        ], dtype=float32)

In [56]:
state = tf.convert_to_tensor(space)

In [57]:
state = tf.convert_to_tensor(state)
state = tf.reshape(state, (1, len(state)))

action_probs, critic_val = model(state)

In [58]:
action_probs

<tf.Tensor: shape=(1, 4), dtype=float32, numpy=array([[0.31890666, 0.17685933, 0.24910223, 0.25513178]], dtype=float32)>

In [59]:
critic_val

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[0.25513676]], dtype=float32)>

In [60]:
action = np.random.choice(env.action_space.n, p = np.squeeze(action_probs))

In [61]:
action

1

In [45]:
np.squeeze(action_probs)

array([0.24676606, 0.25266385, 0.25108433, 0.24948576], dtype=float32)

In [46]:
env.action_space.n

2

In [63]:
action_probs_episodes = []
critic_val_episodes = []


In [70]:
episode_reward = 0

In [67]:
rewards_history = []

In [64]:
action_probs_episodes.append(tf.math.log(action_probs[0, action]))

In [65]:
state, reward, done, _ = env.step(action)

In [66]:
state

array([ 0.0061492 ,  1.385767  ,  0.30536947, -0.57200074, -0.00524055,
       -0.03282565,  0.        ,  0.        ], dtype=float32)

In [71]:
rewards_history.append(reward)
episode_reward += reward